C++ program for rotating donut imagery
xHyroM/hacktoberfest pull request #2
Opened 2022-10-05 11:57 UTC by Shivaminc

2022-10-05 14:20 UTC, xHyroM approved these changes

2022-10-05 14:20 UTC, xHyroM requested changes
You should add it into C++ folder https://github.com/xHyroM/hacktoberfest/tree/master/code/C%2B%2B with .cpp extension

2022-10-06 20:27 UTC, Shivaminc commented
added program to c++ directory.

2022-10-08 05:03 UTC, closed without merging

2022-10-08 05:04 UTC, xHyroM commented
Replaced by your 2nd PR